---
#/ip pool
# add name= ranges=xx.xx.xx.xx-xx.xx.xx.xx
- name: DHCP Server IP Pool
  community.routeros.api_modify:
    path: "ip pool"
    data:
      - name: "{{ item.name }}"
        ranges: "{{ item.ranges }}"
        next-pool: "{{ item.next_pool | default(omit) }}"
        comment: "{{ item.next_pool | default(omit) }}"
  loop:
    - { name: "{{ dhcp_server.pool_name }}", ranges: "{{ dhcp_server.pool_range }}" }

#/ip dhcp-server
# add address-pool=dhcp_pool_vlan1 interface=vlan1 lease-time=1h name=dhcp1
- name: DHCP Server Config
  community.routeros.api_modify:
    path: "ip dhcp-server"
    data:
      - name: "{{ item.name }}"
        interface: "{{ item.interface }}"
        address-pool: "{{ item.address_pool | default(omit) }}"
        allow-dual-stack-queue: "{{ item.allow_dual_stack_queue | default(omit) }}"
        always-broadcast: "{{ item.always_broadcast | default(omit) }}"
        authoritative: "{{ item.authoritative | default(omit) }}"
        bootp-lease-time: "{{ item.bootp_lease_time | default(omit) }}"
        bootp-support: "{{ item.bootp_support | default(omit) }}"
        client-mac-limit: "{{ item.client_mac_limit | default(omit) }}"
        comment: "{{ item.comment | default(omit) }}"
        conflict-detection: "{{ item.conflict_detection | default(omit) }}"
        delay-threshold: "{{ item.delay_threshold | default(omit) }}"
        dhcp-option-set: "{{ item.dhcp_option_set | default(omit) }}"
        disabled: "{{ item.disabled | default(omit) }}"
        insert-queue-before: "{{ item.insert_queue_before | default(omit) }}"
        lease-script: "{{ item.lease_script | default(omit) }}"
        lease-time: "{{ item.lease_time | default(omit) }}"
        parent-queue: "{{ item.parent_queue | default(omit) }}"
        relay: "{{ item.relay | default(omit) }}"
        server-address: "{{ item.server_address | default(omit) }}"
        use-framed-as-classless: "{{ item.use_framed_as_classless | default(omit) }}"
        use-radius: "{{ item.use_radius | default(omit) }}"
  loop:
    - { name: dhcp1, interface: "{{ vlan1.name }}", address_pool: "{{ dhcp_server.pool_name }}", lease_time: "1h"}
#
#/ip dhcp-server network
# add address=xx.xx.xx.xx/24 dns-server=xx.xx.xx.xx gateway=xx.xx.xx.xx
- name: DHCP Server Network Config
  community.routeros.api_modify:
    path: "ip dhcp-server network"
    data:
      - address: "{{ item.address }}"
        dns-server: "{{ item.dns_server }}"
        boot-file-name: "{{ item.boot_file_name | default(omit) }}"
        caps-manager: "{{ item.caps_manager | default(omit) }}"
        comment: "{{ item.comment | default(omit) }}"
        dhcp-option: "{{ item.dhcp_option | default(omit) }}"
        dhcp-option-set: "{{ item.dhcp_option_set | default(omit) }}"
        dns-none: "{{ item.dns_none | default(omit) }}"
        domain: "{{ item.domain | default(omit) }}"
        gateway: "{{ item.gateway | default(omit) }}"
        netmask: "{{ item.netmask | default(omit) }}"
        next-server: "{{ item.next_server | default(omit) }}"
        ntp-server: "{{ item.ntp_server | default(omit) }}"
        wins-server: "{{ item.wins_server | default(omit) }}"
  loop:
    - {  address: "{{ dhcp_server.network }}",  dns_server: "{{ dhcp_server.dns_server }}", gateway: "{{ dhcp_server.gateway }}" }
