---
# Don't need POE on, so safer for it to be off
- name: Ethernet Port Settings
  community.routeros.api_find_and_modify:
    path: "interface ethernet"
    find:
      name: "{{ item['name'] }}"
    values:
      default-name: "{{ item['default-name'] | default(omit) }}"
      advertise: "{{ item['advertise'] | default(omit) }}"
      arp: "{{ item['arp'] | default(omit) }}"
      arp-timeout: "{{ item['arp-timeout'] | default(omit) }}"
      auto-negotiation: "{{ item['auto-negotiation'] | default(omit) }}"
      bandwidth: "{{ item['bandwidth'] | default(omit) }}"
      combo-mode: "{{ item['combo-mode'] | default(omit) }}"
      comment: "{{ item['comment'] | default(omit) }}"
      disabled: "{{ item['disabled'] | default(omit) }}"
      fec-mode: "{{ item['fec-mode'] | default(omit) }}"
      full-duplex: "{{ item['full-duplex'] | default(omit) }}"
      l2mtu: "{{ item.l2mtu | default(omit) }}"
      loop-protect: "{{ item['loop-protect'] | default(omit) }}"
      loop-protect-disable-time: "{{ item['loop-protect-disable-time'] | default(omit) }}"
      loop-protect-send-interval: "{{ item['loop-protect-send-interval'] | default(omit) }}"
      mac-address: "{{ item['mac-address'] | default(omit) }}"
      mdix-enable: "{{ item['mdix-enable'] | default(omit) }}"
      mtu: "{{ item['mtu'] | default(omit) }}"
      name: "{{ item['name'] | default(omit) }}"
      orig-mac-address: "{{ item['orig-mac-address'] | default(omit) }}"
      poe-out: "{{ item['poe-out'] | default(omit) }}"
      poe-priority: "{{ item['poe-priority'] | default(omit) }}"
      poe-voltage: "{{ item['poe-voltage'] | default(omit) }}"
      power-cycle-interval: "{{ item['power-cycle-interval'] | default(omit) }}"
      power-cycle-ping-address: "{{ item['power-cycle-ping-address'] | default(omit) }}"
      power-cycle-ping-enabled: "{{ item['power-cycle-ping-enabled'] | default(omit) }}"
      power-cycle-ping-timeout: "{{ item['power-cycle-ping-timeout'] | default(omit) }}"
      rx-flow-control: "{{ item['rx-flow-control'] | default(omit) }}"
      sfp-rate-select: "{{ item['sfp-rate-select'] | default(omit) }}"
      sfp-shutdown-temperature: "{{ item['sfp-shutdown-temperature'] | default(omit) }}"
      speed: "{{ item['speed'] | default(omit) }}"
      tx-flow-control: "{{ item['tx-flow-control'] | default(omit) }}"
  loop: "{{ ethernet_interfaces }}"
