---
# Don't need POE on, so safer for it to be off
- name: Ethernet Port Settings
  community.routeros.api_find_and_modify:
    path: "interface ethernet"
    find:
      name: "{{ item.name }}"
    values:
      default-name: "{{ item.default_name | default(omit) }}"
      advertise: "{{ item.advertise | default(omit) }}"
      arp: "{{ item.arp | default(omit) }}"
      arp-timeout: "{{ item.arp_timeout | default(omit) }}"
      auto-negotiation: "{{ item.auto_negotiation | default(omit) }}"
      bandwidth: "{{ item.bandwidth | default(omit) }}"
      combo-mode: "{{ item.combo_mode | default(omit) }}"
      comment: "{{ item.comment | default(omit) }}"
      disabled: "{{ item.disabled | default(omit) }}"
      fec-mode: "{{ item.fec_mode | default(omit) }}"
      full-duplex: "{{ item.full_duplex | default(omit) }}"
      l2mtu: "{{ item.l2mtu | default(omit) }}"
      loop-protect: "{{ item.loop_protect | default(omit) }}"
      loop-protect-disable-time: "{{ item.loop_protect_disable_time | default(omit) }}"
      loop-protect-send-interval: "{{ item.loop_protect_send_interval | default(omit) }}"
      mac-address: "{{ item.mac_address | default(omit) }}"
      mdix-enable: "{{ item.mdix_enable | default(omit) }}"
      mtu: "{{ item.mtu | default(omit) }}"
      name: "{{ item.name | default(omit) }}"
      orig-mac-address: "{{ item.orig_mac_address | default(omit) }}"
      poe-out: "{{ item.poe_out | default(omit) }}"
      poe-priority: "{{ item.poe_priority | default(omit) }}"
      poe-voltage: "{{ item.poe_voltage | default(omit) }}"
      power-cycle-interval: "{{ item.power_cycle_interval | default(omit) }}"
      power-cycle-ping-address: "{{ item.power_cycle_ping_address | default(omit) }}"
      power-cycle-ping-enabled: "{{ item.power_cycle_ping_enabled | default(omit) }}"
      power-cycle-ping-timeout: "{{ item.power_cycle_ping_timeout | default(omit) }}"
      rx-flow-control: "{{ item.rx_flow_control | default(omit) }}"
      sfp-rate-select: "{{ item.sfp_rate_select | default(omit) }}"
      sfp-shutdown-temperature: "{{ item.sfp_shutdown_temperature | default(omit) }}"
      speed: "{{ item.speed | default(omit) }}"
      tx-flow-control: "{{ item.tx_flow_control | default(omit) }}"
  loop: "{{ poe_interfaces }}"
