---
#/ip firewall filter
#  .id looks to be being ignored.
# Router is injecting a rule 0, so .id is always 1 off
# Rule with hw=yes always returned changed, and a duplicate rule is added.
- name: Firewall settings
  community.routeros.api_modify:
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    ensure_order: true
    path: ip firewall filter
    data: "{{ firewall_rules }}"

# Loops don't work with absent handler. Only the last item remains.
#      - action: "{{ item.action }}"
#        chain: "{{ item.chain }}"
#        comment: "{{ item.comment | default(omit) }}"
#        address-list: "{{ item['address-list'] | default(omit) }}"
#        address-list-timeout: "{{ item['address-list-timeout'] | default(omit) }}"
#        connection-bytes: "{{ item['connection-bytes'] | default(omit) }}"
#        connection-limit: "{{ item['connection-limit'] | default(omit) }}"
#        connection-mark: "{{ item['connection-mark'] | default(omit) }}"
#        connection-nat-state: "{{ item['connection-nat-state'] | default(omit) }}"
#        connection-rate: "{{ item['connection-rate'] | default(omit) }}"
#        connection-state: "{{ item['connection-state'] | default(omit) }}"
#        connection-type: "{{ item['connection-type'] | default(omit) }}"
#        content: "{{ item.content | default(omit) }}"
#        disabled: "{{ item.disabled | default(omit) }}"
#        dscp: "{{ item.dscp | default(omit) }}"
#        dst-address: "{{ item['dst-address'] | default(omit) }}"
#        dst-address-list: "{{ item['dst-address-list'] | default(omit) }}"
#        dst-address-type: "{{ item['dst-address-type'] | default(omit) }}"
#        dst-limit: "{{ item['dst-limit'] | default(omit) }}"
#        dst-port: "{{ item['dst-port'] | default(omit) }}"
#        fragment: "{{ item.fragment | default(omit) }}"
#        hotspot: "{{ item.hotspot | default(omit) }}"
#        hw-offload: "{{ item['hw-offload'] | default(omit) }}"
#        icmp-options: "{{ item['icmp-options'] | default(omit) }}"
#        in-bridge-port: "{{ item['in-bridge-port'] | default(omit) }}"
#        in-bridge-port-list: "{{ item['in-bridge-port-list'] | default(omit) }}"
#        in-interface: "{{ item['in-interface'] | default(omit) }}"
#        in-interface-list: "{{ item['in-interface-list'] | default(omit) }}"
#        ingress-priority: "{{ item['ingress-priority'] | default(omit) }}"
#        ipsec-policy: "{{ item['ipsec-policy'] | default(omit) }}"
#        ipv4-options: "{{ item.ipv4_options | default(omit) }}"
#        jump-target: "{{ item['jump-target'] | default(omit) }}"
#        layer7-protocol: "{{ item.layer7_protocol | default(omit) }}"
#        limit: "{{ item.limit | default(omit) }}"
#        log: "{{ item.log | default(omit) }}"
#        log-prefix: "{{ item['log-prefix'] | default(omit) }}"
#        nth: "{{ item.nth | default(omit) }}"
#        out-bridge-port: "{{ item['out-bridge-port'] | default(omit) }}"
#        out-bridge-port-list: "{{ item['out-bridge-port-list'] | default(omit) }}"
#        out-interface: "{{ item['out-interface'] | default(omit) }}"
#        out-interface-list: "{{ item['out-interface-list'] | default(omit) }}"
#        p2p: "{{ item.p2p | default(omit) }}"
#        packet-mark: "{{ item['packet-mark'] | default(omit) }}"
#        packet-size: "{{ item['packet-size'] | default(omit) }}"
#        per-connection-classifier: "{{ item['per-connection-classifier'] | default(omit) }}"
#        port: "{{ item.port | default(omit) }}"
#        priority: "{{ item.priority | default(omit) }}"
#        protocol: "{{ item.protocol | default(omit) }}"
#        psd: "{{ item.psd | default(omit) }}"
#        random: "{{ item.random | default(omit) }}"
#        realm: "{{ item.realm | default(omit) }}"
#        reject-with: "{{ item['reject-with'] | default(omit) }}"
#        routing-mark: "{{ item['routing-mark'] | default(omit) }}"
#        routing-table: "{{ item['routing-table'] | default(omit) }}"
#        src-address: "{{ item['src-address'] | default(omit) }}"
#        src-address-list: "{{ item['src-address-list'] | default(omit) }}"
#        src-address-type: "{{ item['src-address-type'] | default(omit) }}"
#        src-mac-address: "{{ item['src-mac-address'] | default(omit) }}"
#        src-port: "{{ item['src-port'] | default(omit) }}"
#        tcp-flags: "{{ item['tcp-flags'] | default(omit) }}"
#        tcp-mss: "{{ item['tcp-mss'] | default(omit) }}"
#        time: "{{ item.time | default(omit) }}"
#        tls-host: "{{ item['tls-host'] | default(omit) }}"
#        ttl: "{{ item.ttl | default(omit) }}"
#         # .id: "*{{ rindex + 1 }}"
#  loop: "{{ firewall_rules }}"
#  loop_control:
#    index_var: rindex
#
