---
#/interface list
# add name=WAN
# add name=LAN
- name: Interface List Settings
  community.routeros.api_modify:
    path: "interface list"
    data:
      - name: "{{ item.name }}"
        comment: "{{ item.comment | default(omit) }}"
        exclude: "{{ item.exclude | default(omit) }}"
        include: "{{ item.include | default(omit) }}"
  loop: "{{ interface_lists }}"

# WARNING. This step looks to be breaking connectivity
# unless networking is set up on these vlans
# /interface list member
# add interface=vlan10 list=WAN
# add interface=bridge1 list=LAN
- name: Interface List Members
  community.routeros.api_modify:
    path: "interface list member"
    data:
      - list: "{{ item.name }}"
        interface: "{{ item.interface }}"
        comment: "{{ item.comment | default(omit) }}"
        disabled: "{{ item.disabled | default(omit) }}"
  loop: "{{ interface_lists }}"
