---
# This is our internal LAN vlan
# also need to loop over bridge and ethernet interfaces, looking for static IP settings.
- name: build VLAN IP settings ip_list
  ansible.builtin.set_fact:
    ip_list: >
      {{
        ip_list | default([]) +
        [{
          'interface': item.1.name,
          'address': item.1.ip_settings.static.ip + '/' + item.1.ip_settings.static.mask_bits,
          'network': item.1.ip_settings.static.network,
          'comment': item.1.comment | default(omit),
          'disabled': item.1.disabled | default(omit)
        }]
      }}
  when: item.1.ip_settings is defined and item.1.ip_settings.static is defined
  with_subelements:
    - "{{ bridge }}"
    - interface_vlans
    - skip_missing: True

- name: Add Bridge IP settings to ip_list
  ansible.builtin.set_fact:
    ip_list: >
      {{
        ip_list | default([]) +
        [{
          'interface': item.name,
          'address': item.ip_settings.static.ip + '/' + item.ip_settings.static.mask_bits,
          'network': item.ip_settings.static.network,
          'comment': item.comment | default(omit),
          'disabled': item.disabled | default(omit)
        }]
      }}
  when: item.ip_settings is defined and item.ip_settings.static is defined
  loop: "{{ bridge }}"

- name: Add ethernet IP settings to ip_list
  ansible.builtin.set_fact:
    ip_list: >
      {{
        ip_list | default([]) +
        [{
          'interface': item.name,
          'address': item.ip_settings.static.ip + '/' + item.ip_settings.static.mask_bits,
          'network': item.ip_settings.static.network,
          'comment': item.comment | default(omit),
          'disabled': item.disabled | default(omit)
        }]
      }}
  when: item.ip_settings is defined and item.ip_settings.static is defined
  loop: "{{ ethernet_interfaces }}"

- name: Debug ip_list
  ansible.builtin.debug:
    var: ip_list
  when: ip_list is defined


- name: Interface IP Settings
  community.routeros.api_modify:
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    path: "ip address"
    data: "{{ ip_list }}"
