---
# Don't need POE on, so safer for it to be off
- name: Disable POE where we aren't using it
  community.routeros.api_find_and_modify:
    path: "interface ethernet"
    find:
      name: "{{ item.name }}"
    values:
      poe-out: "{{ item.state }}"
  loop: "{{ poe_interfaces }}"


#'default-name': KeyInfo(),
#'advertise': KeyInfo(),
#'arp': KeyInfo(default='enabled'),
#'arp-timeout': KeyInfo(default='auto'),
#'auto-negotiation': KeyInfo(default=True),
#'bandwidth': KeyInfo(default='unlimited/unlimited'),
#'combo-mode': KeyInfo(can_disable=True),
#'comment': KeyInfo(can_disable=True, remove_value=''),
#'disabled': KeyInfo(default=False),
#'fec-mode': KeyInfo(can_disable=True, remove_value='auto'),
#'full-duplex': KeyInfo(default=True),
#'l2mtu': KeyInfo(),
#'loop-protect': KeyInfo(default='default'),
#'loop-protect-disable-time': KeyInfo(default='5m'),
#'loop-protect-send-interval': KeyInfo(default='5s'),
#'mac-address': KeyInfo(),
#'mdix-enable': KeyInfo(),
#'mtu': KeyInfo(default=1500),
#'name': KeyInfo(),
#'orig-mac-address': KeyInfo(),
#'poe-out': KeyInfo(can_disable=True, remove_value='auto-on'),
#'poe-priority': KeyInfo(can_disable=True, remove_value=10),
#'poe-voltage': KeyInfo(can_disable=True),
#'power-cycle-interval': KeyInfo(),
#'power-cycle-ping-address': KeyInfo(can_disable=True),
#'power-cycle-ping-enabled': KeyInfo(),
#'power-cycle-ping-timeout': KeyInfo(can_disable=True),
#'rx-flow-control': KeyInfo(default='off'),
#'sfp-rate-select': KeyInfo(default='high'),
#'sfp-shutdown-temperature': KeyInfo(default=95),
#'speed': KeyInfo(),
#'tx-flow-control': KeyInfo(default='off'),
