---
# /ip route
#add dst-address=10.0.0.0/8 gateway={{ lan_gw }}
#add dst-address=192.168.0.0/16 gateway={{ lan_gw }}
#add dst-address=100.64.0.0/24 gateway={{ lan_gw }}
- name: Set LAN routes
  community.routeros.api_modify:
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    path: "ip route"
    data: "{{ routes }}"
#      - dst-address: "{{ item['dst-address'] | default(omit) }}"
#        blackhole: "{{ item.blackhole | default(omit) }}"
#        check-gateway: "{{ item['check-gateway'] | default(omit) }}"
#        comment: "{{ item.comment | default(omit) }}"
#        disabled: "{{ item.disabled | default(omit) }}"
#        distance: "{{ item.distance | default(omit) }}"
#        gateway: "{{ item.gateway | default(omit) }}"
#        pref-src: "{{ item['pref-src'] | default(omit) }}"
#        routing-table: "{{ item['routing-table'] | default(omit) }}"
#        route-tag: "{{ item['route-tag'] | default(omit) }}"
#        routing-mark: "{{ item['routing-mark'] | default(omit) }}"
#        scope: "{{ item.scope | default(omit) }}"
#        suppress-hw-offload: "{{ item['suppress-hw-offload'] | default(omit) }}"
#        target-scope: "{{ item['target-scope'] | default(omit) }}"
#        type: "{{ item.type | default(omit) }}"
#        vrf-interface: "{{ item['vrf-interface'] | default(omit) }}"
#  loop: "{{ routes }}"
