---
# /ip route
#add dst-address=10.0.0.0/8 gateway={{ lan_gw }}
#add dst-address=192.168.0.0/16 gateway={{ lan_gw }}
#add dst-address=100.64.0.0/24 gateway={{ lan_gw }}
- name: Set LAN routes
  community.routeros.api_modify:
    path: "ip route"
    data:
      - dst-address: "{{ item.dst_address | default(omit) }}"
        blackhole: "{{ item.blackhole | default(omit) }}"
        check-gateway: "{{ item.check_gateway | default(omit) }}"
        comment: "{{ item.comment | default(omit) }}"
        disabled: "{{ item.disabled | default(omit) }}"
        distance: "{{ item.distance | default(omit) }}"
        gateway: "{{ item.gateway | default(omit) }}"
        pref-src: "{{ item.pref_src | default(omit) }}"
        routing-table: "{{ item.routing_table | default(omit) }}"
        route-tag: "{{ item.route_tag | default(omit) }}"
        routing-mark: "{{ item.routing_mark | default(omit) }}"
        scope: "{{ item.scope | default(omit) }}"
        suppress-hw-offload: "{{ item.suppress_hw_offload | default(omit) }}"
        target-scope: "{{ item.target_scope | default(omit) }}"
        type: "{{ item.type | default(omit) }}"
        vrf-interface: "{{ item.vrf_interface | default(omit) }}"
  loop: "{{ lan_routes }}"
