---
#/interface ethernet switch vlan
#add independent-learning=yes ports=ether1,switch1-cpu switch=switch1 vlan-id=10
#add independent-learning=yes ports=ether2,ether3,ether4,ether5,switch1-cpu switch=switch1 vlan-id=1

- name: build switch vlan list
  ansible.builtin.set_fact:
    #      bridge:
    #      vlan-ids:
    #      tagged:
    #      untagged:
    #      comment:
    bridge_interface_vlans: >
      {{
        switch_interface_vlans | default([]) +
        [
          item.1 | dict2items
          | selectattr('key', 'in', ['vlan-ids','tagged','untagged','comment'])
          | items2dict
          | combine( { 'bridge': item.0.name } )
        ]
      }}
  with_subelements:
    - "{{ bridge }}"
    - interface_vlans
    - skip_missing: True

- name: Debug bridge Interface vlans
  ansible.builtin.debug:
    var: bridge_interface_vlans

- name: Configure VLANs on the bridge
  community.routeros.api_modify:
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    path: "interface bridge vlan"
    data: "{{ bridge_interface_vlans }}"
