---
#/interface vlan
# add interface=bridge1 name=vlan10 vlan-id=10
# add interface=bridge1 name=vlan1 vlan-id=1
# Still need to do the reverse, with /interface bridge vlan add ... ?

- name: Add VLAN 1 and 10 to bridge
  community.routeros.api_modify:
    path: "interface vlan"
    data:
      - name: "{{ item.name }}"
        interface: "{{ item.interface }}"
        arp: "{{ item.arp | default(omit) }}"
        arp-timeout: "{{ item.arp_timeout | default(omit) }}"
        comment: "{{ item.comment | default(omit) }}"
        disabled: "{{ item.disabled | default(omit) }}"
        loop-protect: "{{ item.loop_protect | default(omit) }}"
        loop-protect-disable-time: "{{ item.loop_protect_disable_time | default(omit) }}"
        loop-protect-send-interval: "{{ item.loop_protect_send_interval | default(omit) }}"
        mtu: "{{ item.mtu | default(omit) }}"
        use-service-tag: "{{ item.use_service_tag | default(omit) }}"
        vlan-id: "{{ item.vlan_id | default(omit) }}"
  loop:
    - { name: "vlan1", interface: "{{ bridge.name }}", vlan_id: "1" }
    - { name: "vlan10", interface: "{{ bridge.name }}", vlan_id: "10" }
    - { name: "vlan88", interface: "{{ bridge.name }}", vlan_id: "88" }
