---
- name: Configure Mikrotik as Fibre Modem
  hosts: mikrotik
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      password: "{{ ansible_api_pass }}"
      username: "{{ ansible_user }}"
      # The following options configure TLS/SSL.
      # Depending on your setup, these options need different values:
      tls: false
      validate_certs: false
      validate_cert_hostname: false
      # If you are using your own PKI, specify the path to your CA certificate here:
      # ca_path: /path/to/ca-certificate.pem
      #
  vars:
    routeros_hostname: fibre2
    routeros_domainname: wikarekare.org

  #  tasks:
  #    - name: Gather facts
  #      community.routeros.api_facts:

  roles:
    - gather_facts
    - host_config
    - networking
