firewall_rules:
  # input chain
  - { action: accept, chain: input, comment: "accept established,related,untracked", connection_state: "established,related,untracked" }
  - { action: drop, chain: input, comment: "drop invalid", connection_state: "invalid" }
  - { action: accept, chain: input, comment: "accept ICMP", protocol: icmp }
  - { action: accept, chain: input, comment: "accept to local loopback (for CAPsMAN)", dst_address: "127.0.0.1" }
  - { action: accept, chain: input, comment: "Allow Management Port", in_interface_list: "MGMT" }
  - { action: drop, chain: input, comment: "drop all not coming from LAN", in_interface_list: "!LAN" }
  # Forward chain
  - { action: accept, chain: forward, comment: "accept in ipsec policy", ipsec_policy: "in,ipsec" }
  - { action: accept, chain: forward, comment: "accept out ipsec policy", ipsec_policy: "out,ipsec" }
  # the following rule get duplicated every run
  - { action: "fasttrack-connection", chain: forward, comment: "fasttrack", connection_state: "established,related", hw_offload: "yes"}
  - { action: accept, chain: forward, comment: "accept established,related,untracked", connection_state: "established,related,untracked" }
  - { action: drop, chain: forward, comment: "drop invalid", connection_state: "invalid" }
  - { action: drop, chain: forward, comment: "drop all from WAN not DSTNATed", connection_nat_state: "!dstnat", connection_state: "new", in_interface_list: "WAN" }
nat_rules:
  - { action: masquerade, chain: srcnat, comment: "masquerade", ipsec_policy: "out,none", out_interface_list: "WAN" }
