---
- name: Enable SNMP
  community.routeros.api_modify:
    path: "snmp"
    data:
      - enabled: "yes"
        contact: "Rob Burrowes, rob@wikarekare.org"
        location: "OceanView Cabinet"

- name: Set SNMP Parameters
  community.routeros.api_modify:
    path: "snmp community"
    handle_absent_entries: remove
    data:
      - name: "public"
        read-access: "no"
        write-access: "no"
      - name: "wikk_ovc_ro"
        read-access: "yes"
        write-access: "no"
        addresses: "100.64.0.0/16"
