---
- name: Enable SNMP
  community.routeros.api_modify:
    path: "snmp"
    data: "{{ snmp.config }}"

- name: Set SNMP Parameters
  community.routeros.api_modify:
    path: "snmp community"
    handle_absent_entries: remove
    data: "{{ snmp.community }}"
